version: '3.7'
services:
    db:
        image: mysql:5.7.29
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db
        extra_hosts:
            - "docker.host:127.0.0.1"
        depends_on:
            - redis
        environment:
            - WAIT_HOSTS=redis:6379
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached

    redis:
        image: "redis:alpine"
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
          - "./volumes/redis:/data"
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"